### ISSUE TITLE
New viz: pairwise cross coalescence plots

### ISSUE THREAD

**Issue by hyanwong** [percyfal/tseda#1]
As per slack:

> I was imagining having a matrix of plots (like R `pairs()` or [Nate's example](https://github.com/nspope/coaldecoder?tab=readme-ov-file#demographic-parameter-estimates), but e.g. with a heat maps, including on the diagonal), showing relatively small thumbnail-like subplots of combinations of subpopulations, and with a much larger single plot in a panel above, When you mouse over a particular subplot in the pairs matrix, the edges relevant to that pair are highlighted in the large plot. If you mouse over any of the subplots on the diagonal, the edges relevant to that population only are highlighted (as if you had simplified()  the tree sequence to only samples from that population).

**Comment by percyfal** [comment]
Transferred to https://github.com/tforest/tseda/issues/9
