### ISSUE TITLE
New viz: recombinational suppression / inversions

### ISSUE THREAD

**Issue by hyanwong** [percyfal/tseda#3]
I think there should be some way to be able to visualise recombinational suppression along the chromosome, perhaps split by clade, which would be able to highlight e.g. inversions. 

There's an known inversion on chr17p of humans (https://www.nature.com/articles/ng1508), and some others picked up in https://www.biorxiv.org/content/10.1101/2023.07.11.548567v2.full.pdf. I chatted to Ana about possible visualisations, and she was unsure how well a viz would work (as opposed to plotting p-values as below), but I think it's worth exploring. Probably a good way to do this is to take the recent 1000 genomes chr17 inferred tree sequence and mess with visualizations (e.g. edge /clade spans in cM ploted against frequency and coloured by age or against age and coloured by freq), to see if the know inversion starts to stand out at all.

<img width="961" alt="Screenshot 2024-08-31 at 11 35 52" src="https://github.com/user-attachments/assets/1d662b52-d2c7-4827-a1cc-f63d226cc8de">

Jessica Purcell's ant system would be another nice example to use to try on real genealogies.

**Comment by percyfal** [comment]
Transferred to https://github.com/tforest/tseda/issues/7
