### ISSUE TITLE
New viz: graphical equivalent of the Relate test, for spotting selective sweeps

### ISSUE THREAD

**Issue by hyanwong** [percyfal/tseda#5]
The idea of the Relate test is very simple: you highlight a clade (often defined by a mutation) and look at how the number of descendant lineages change over time, usually just comparing the frequency in the current day with the frequency of other lineages that originated at the same time.

There should be a nice graphic way to show this, e.g. by mousing over a mutation in a mutation-time vs location plot, and showing a (relative) frequency trajectory, or something. Perhaps this could be tied in to the very visible edge-plot patterns too (below). I haven't thought very hard about exactly what to plot here, though.

![image](https://github.com/user-attachments/assets/40a0ee89-752c-4473-ac0e-49475614230b)

**Comment by percyfal** [comment]
Transferred to https://github.com/tforest/tseda/issues/6
