### ISSUE TITLE
Can't get GNN haplotype plots to work

### ISSUE THREAD

**Issue by hyanwong** [percyfal/tseda#6]
Using the test tree seq, I type a number in the box shown below, press return, but nothing seems to happen. The "busy" indicator seems not to be doing anything, so I don't think it's waiting on calculations?

<img width="601" alt="Screenshot 2024-09-02 at 09 39 47" src="https://github.com/user-attachments/assets/69ad6e7d-35df-40d0-8b3a-ab0952ea99c8">

**Comment by percyfal** [comment]
Haha - no the page is just a placeholder, no code yet that actually draws the GNNs...

**Comment by percyfal** [comment]
I should probably add a note about that on the page
